name: Deploy to DockerHub

on:
  push:
    branches:
      - main  # Change to release branch if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          cd server
          docker build -t yourdockerhubusername/fullstackflush-server:latest .
          docker tag yourdockerhubusername/fullstackflush-server:latest yourdockerhubusername/fullstackflush-server:v1
          docker push yourdockerhubusername/fullstackflush-server:latest
          docker push yourdockerhubusername/fullstackflush-server:v1

      - name: Build and Push Frontend Image
        run: |
          cd client
          docker build -t yourdockerhubusername/fullstackflush-client:latest .
          docker tag yourdockerhubusername/fullstackflush-client:latest yourdockerhubusername/fullstackflush-client:v1
          docker push yourdockerhubusername/fullstackflush-client:latest
          docker push yourdockerhubusername/fullstackflush-client:v1

